version: "3.9"
services:

  redis:
    image: redis:7-alpine
    container_name: scribeshade-redis
    restart: always
    volumes:
      - redis_data:/data
  postgres:
    build: .
    container_name: scribeshade-db
    restart: always
    environment:
      POSTGRES_USER: scribe-user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: scribeshade
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: scribeshade-backend:latest
    container_name: scribeshade-api
    restart: always
    ports:
      - "3200:3200"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://scribeshade-redis:6379
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
